/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author bryan
 */
public class Eliminar_producto extends javax.swing.JFrame {

    //variables para mysql
    public static final String DB_URL = "jdbc:mysql://localhost/esfot-care";
    public static final String USER = "root";
    public static final String PASSWORD = "root2023";
    
    /**
     * Creates new form Eliminar_producto
     */
    public Eliminar_producto() {
        initComponents();
        this.setLocationRelativeTo(null);
        desTitle.setVisible(false);
        descriptLabel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        codprodInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        desTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        eliminarProductoButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        descriptLabel = new javax.swing.JLabel();
        jButtonBuscarDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        codprodInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        codprodInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codprodInputMouseClicked(evt);
            }
        });
        codprodInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codprodInputActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box-open-full.png"))); // NOI18N

        desTitle.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        desTitle.setText("Descripción:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel3.setText("Eliminar Producto");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel4.setText("Código del producto:");

        eliminarProductoButton.setBackground(new java.awt.Color(204, 204, 255));
        eliminarProductoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarProductoButton.setText("Eliminar Producto");
        eliminarProductoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarProductoButtonMouseClicked(evt);
            }
        });
        eliminarProductoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProductoButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 204, 204));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        descriptLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButtonBuscarDelete.setText("Buscar");
        jButtonBuscarDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(eliminarProductoButton)
                                .addGap(107, 107, 107)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descriptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(139, 139, 139)))
                        .addGap(57, 87, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desTitle)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codprodInput, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBuscarDelete)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(codprodInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarDelete))
                .addGap(31, 31, 31)
                .addComponent(desTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarProductoButton)
                    .addComponent(cancelButton))
                .addGap(58, 58, 58))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void eliminarProductoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarProductoButtonMouseClicked
        JOptionPane.showMessageDialog(null, "El producto de código: ----- \n ha sido eliminado con éxito.", "Producto Eliminado",JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
    }//GEN-LAST:event_eliminarProductoButtonMouseClicked

    private void codprodInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codprodInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codprodInputActionPerformed

    private void codprodInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codprodInputMouseClicked
        desTitle.setVisible(true);
        descriptLabel.setVisible(true);
    }//GEN-LAST:event_codprodInputMouseClicked

    private void eliminarProductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductoButtonActionPerformed
       String cod = codprodInput.getText();

        try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASSWORD)) {
            String DELETE_QUERY = "DELETE FROM productos WHERE codigo_prod = ?";

            conn.setAutoCommit(false);

            PreparedStatement deleteStmt = conn.prepareStatement(DELETE_QUERY);
            deleteStmt.setString(1, cod);

            int rowsAffected = deleteStmt.executeUpdate();

            if (rowsAffected > 0) {
                conn.commit();
                JOptionPane.showMessageDialog(null, "Producto eliminado exitosamente");
                this.setVisible(false);
            } else {
                conn.rollback();
                JOptionPane.showMessageDialog(null, "Error al eliminar el cajero, intentelo nuevamente.");
            }
        } catch (SQLException x) {
            throw new RuntimeException(x);
        }
    }//GEN-LAST:event_eliminarProductoButtonActionPerformed

    private void jButtonBuscarDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarDeleteActionPerformed
        // TODO add your handling code here:
        String cod = codprodInput.getText();
        
        try (Connection conn = DriverManager.getConnection(DB_URL, USER, PASSWORD)) {
        String Query = "SELECT * FROM productos WHERE codigo_prod = ?";
        PreparedStatement stmt = conn.prepareStatement(Query);
        stmt.setString(1, cod);

        ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                String nombreProd = rs.getString("nombre_prod");
                
                descriptLabel.setText(nombreProd);
                
            } else {
                JOptionPane.showMessageDialog(null, "No existe este producto, ingrese el cosigo correcto.");
            }
        } catch (SQLException x) {
            throw new RuntimeException(x);
        }
        
    }//GEN-LAST:event_jButtonBuscarDeleteActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField codprodInput;
    private javax.swing.JLabel desTitle;
    private javax.swing.JLabel descriptLabel;
    private javax.swing.JButton eliminarProductoButton;
    private javax.swing.JButton jButtonBuscarDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
