package Vista;
import javax.swing.*;

/**
 *
 * @author bryan
 */
public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Sistema de Gestión Comercial | ESFOT-Care+");
    }
    
    //Objeto para la clase de conexion a la base de datos
    DatabaseConnection dbConnect = new DatabaseConnection();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        adminTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        admiInput = new javax.swing.JTextField();
        pass_admiInput = new javax.swing.JPasswordField();
        ingresarButton = new javax.swing.JButton();
        cajeroTab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cajeroInput = new javax.swing.JTextField();
        cajero_passInput = new javax.swing.JPasswordField();
        ingresarButton2 = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 204));
        jTabbedPane1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setText("Cédula / Código de administ.:");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setText("Contraseña:");

        ingresarButton.setBackground(new java.awt.Color(204, 255, 255));
        ingresarButton.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        ingresarButton.setText("Ingresar al sistema");
        ingresarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarButtonMouseClicked(evt);
            }
        });
        ingresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminTabLayout = new javax.swing.GroupLayout(adminTab);
        adminTab.setLayout(adminTabLayout);
        adminTabLayout.setHorizontalGroup(
            adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTabLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingresarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(admiInput)
                        .addComponent(pass_admiInput, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        adminTabLayout.setVerticalGroup(
            adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTabLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pass_admiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(ingresarButton)
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Administrador/a   ", new javax.swing.ImageIcon(getClass().getResource("/Images/profile.png")), adminTab); // NOI18N
        adminTab.getAccessibleContext().setAccessibleName("adminTab");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setText("Cédula / Código de cajero:");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setText("Contraseña:");

        ingresarButton2.setBackground(new java.awt.Color(204, 255, 204));
        ingresarButton2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        ingresarButton2.setText("Ingresar al sistema");
        ingresarButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarButton2MouseClicked(evt);
            }
        });
        ingresarButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cajeroTabLayout = new javax.swing.GroupLayout(cajeroTab);
        cajeroTab.setLayout(cajeroTabLayout);
        cajeroTabLayout.setHorizontalGroup(
            cajeroTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajeroTabLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(cajeroTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(cajeroTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingresarButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addGroup(cajeroTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cajeroInput, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(cajero_passInput)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        cajeroTabLayout.setVerticalGroup(
            cajeroTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajeroTabLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(cajeroTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cajeroInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(cajeroTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cajero_passInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(ingresarButton2)
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Cajero/a    ", new javax.swing.ImageIcon(getClass().getResource("/Images/package.png")), cajeroTab); // NOI18N
        cajeroTab.getAccessibleContext().setAccessibleName("cajeroTab");

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 510, 320));
        jTabbedPane1.getAccessibleContext().setAccessibleName("usertypePanel");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_2.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 260, 120));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/radiant-gradient.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String cod_adm;
    public static String cod_caj;
    private void ingresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarButtonActionPerformed
        cod_adm = admiInput.getText();
        String ci_adm = admiInput.getText();
        //tipo password como String
        String password_adm = String.valueOf(pass_admiInput.getPassword());

        boolean inicioCorrecto_adm = dbConnect.iniciarSesionDB("administradores","codigo_admin","ci_admin","password_admin",cod_adm,ci_adm,password_adm);

        if(!inicioCorrecto_adm){
            JOptionPane.showMessageDialog(null,"Usuario o contraseña incorrectos!","Error",JOptionPane.ERROR_MESSAGE);
            limpiarRegistro(admiInput,pass_admiInput);
        } 
    }//GEN-LAST:event_ingresarButtonActionPerformed

    public static String getCod_adm() {
        return cod_adm;
    }
    
    public static String getCod_caj() {
        return cod_caj;
    }

    private void ingresarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarButton2ActionPerformed
        cod_caj = cajeroInput.getText();
        String ci_caj = cajeroInput.getText();
        //tipo password como String
        String password_caj = String.valueOf(cajero_passInput.getPassword());

        boolean inicioCorrecto_caj = dbConnect.iniciarSesionDB("cajeros","codigo_caj","ci_caj","password_caj",cod_caj,ci_caj,password_caj);

        if(!inicioCorrecto_caj){
            JOptionPane.showMessageDialog(null,"Usuario o contraseña incorrectos!","Error",JOptionPane.ERROR_MESSAGE);
            limpiarRegistro(cajeroInput,cajero_passInput);
        }        
    }//GEN-LAST:event_ingresarButton2ActionPerformed

    private void ingresarButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarButton2MouseClicked
         Home_Cajero cajero = new Home_Cajero();
         
         cajero.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_ingresarButton2MouseClicked

    private void ingresarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarButtonMouseClicked
        this.setVisible(false); 
        Home_Admin admin = new Home_Admin();
        admin.setVisible(true);
    }//GEN-LAST:event_ingresarButtonMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admiInput;
    private javax.swing.JPanel adminTab;
    private javax.swing.JLabel background;
    private javax.swing.JTextField cajeroInput;
    private javax.swing.JPanel cajeroTab;
    private javax.swing.JPasswordField cajero_passInput;
    private javax.swing.JButton ingresarButton;
    private javax.swing.JButton ingresarButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField pass_admiInput;
    // End of variables declaration//GEN-END:variables

    //metodo para limpieza de campos
    private void limpiarRegistro(JTextField userInput, JPasswordField passInput){
        userInput.setText(null);
        passInput.setText(null);
    }
}


