/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author bryan
 */

public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    
    public static final String DB_URL = "jdbc:mysql://localhost/esfot-care";
    public static final String USER = "root";
    public static final String PASSWORD = "root2023";
    
    public static String codCajero;
    
    public static String nomCompletocaj;
    public static int nVentascaj;
    public static double totalsinIva; 
    public static double totalG;
    public static double totalImp;

    public Reportes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Reportes de Venta | Gestion Administrativa de ESFOT-Care+");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reporteTable = new javax.swing.JTable();
        codCajeroInput = new javax.swing.JTextField();
        jButtonBuscarCajeroCod = new javax.swing.JButton();
        reporteCajeroBtn = new javax.swing.JButton();
        jButtonDesplegarCajeros = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        empleadosMenu = new javax.swing.JMenu();
        inventarioMenu = new javax.swing.JMenu();
        reportesMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Buscar por código de cajero:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        reporteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Num Fact.", "Nombre del Cajero", "Cod. Cajero", "Fecha Emi.", "CI Cliente", "Total Vendido", "Ganancias obtenidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reporteTable);
        if (reporteTable.getColumnModel().getColumnCount() > 0) {
            reporteTable.getColumnModel().getColumn(0).setResizable(false);
            reporteTable.getColumnModel().getColumn(1).setResizable(false);
            reporteTable.getColumnModel().getColumn(2).setResizable(false);
            reporteTable.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 1130, 390));

        codCajeroInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        codCajeroInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codCajeroInputActionPerformed(evt);
            }
        });
        getContentPane().add(codCajeroInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 130, 30));

        jButtonBuscarCajeroCod.setText("Buscar");
        jButtonBuscarCajeroCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCajeroCodActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarCajeroCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 90, 30));

        reporteCajeroBtn.setBackground(new java.awt.Color(204, 255, 204));
        reporteCajeroBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reporteCajeroBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-alt.png"))); // NOI18N
        reporteCajeroBtn.setText("   Generar reporte por cajero");
        reporteCajeroBtn.setActionCommand("  Agregar Producto");
        reporteCajeroBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteCajeroBtnMouseClicked(evt);
            }
        });
        reporteCajeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteCajeroBtnActionPerformed(evt);
            }
        });
        getContentPane().add(reporteCajeroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 270, -1));

        jButtonDesplegarCajeros.setText("Desplegar todo");
        jButtonDesplegarCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesplegarCajerosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDesplegarCajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_2.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, 90));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jLabel4.setText("Reportes de Ventas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/radiant-gradient.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1200, 680));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_2.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, -1, -1));

        homeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        homeMenu.setText("Inicio");
        homeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(homeMenu);

        empleadosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-alt.png"))); // NOI18N
        empleadosMenu.setText("Empleados");
        empleadosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empleadosMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(empleadosMenu);

        inventarioMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box-open-full.png"))); // NOI18N
        inventarioMenu.setText("Inventario");
        inventarioMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventarioMenuMouseClicked(evt);
            }
        });
        inventarioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(inventarioMenu);

        reportesMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/books.png"))); // NOI18N
        reportesMenu.setText("Reportes");
        jMenuBar1.add(reportesMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign-out-alt.png"))); // NOI18N
        jMenu1.setText("Cerrar Sesión");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuMouseClicked
        this.setVisible(false);
        Home_Admin homin = new Home_Admin();
        homin.setVisible(true);
    }//GEN-LAST:event_homeMenuMouseClicked

    private void empleadosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleadosMenuMouseClicked

    }//GEN-LAST:event_empleadosMenuMouseClicked

    private void inventarioMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarioMenuMouseClicked
        Inventario inventario = new Inventario();
        inventario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_inventarioMenuMouseClicked

    private void inventarioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioMenuActionPerformed

    }//GEN-LAST:event_inventarioMenuActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void codCajeroInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codCajeroInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codCajeroInputActionPerformed

    private void jButtonBuscarCajeroCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCajeroCodActionPerformed
        // TODO add your handling code here:
        codCajero=codCajeroInput.getText();
        try(Connection conn = DriverManager.getConnection(DB_URL, USER, PASSWORD)){
            String Query = "SELECT cab.num_factura, " +
                "CONCAT(caj.nombre_caj, ' ', caj.apellido_caj) AS nombreComp_caj, " +
                "caj.codigo_caj, " +
                "cab.fecha_emision, " +
                "cab.Clientes_ci_cli, " +
                "cab.total_pagar, " +
                "cab.subtotal_fac - SUM(valcompra_prod * det.cantidad) AS ganancia_obtenida " +
                "FROM cabecera_fac cab " +
                "INNER JOIN cajeros caj ON caj.codigo_caj = cab.Cajeros_codigo_caj " +
                "INNER JOIN detalle_fac det ON det.Cabecera_Fac_num_factura = cab.num_factura " +
                "INNER JOIN productos pro ON pro.codigo_prod = det.Productos_codigo_prod " +
                "WHERE caj.codigo_caj = ? " + // Filtra por el código del cajero
                "GROUP BY cab.num_factura;";
            PreparedStatement stmt = conn.prepareStatement(Query);
            stmt.setString(1, codCajero);
            ResultSet rs = stmt.executeQuery();

            reporteTable.getModel();

            int row = 0;

            //prueba conexion
            while (rs.next()) {

                reporteTable.setValueAt("", row, 0);
                reporteTable.setValueAt("", row, 1);
                reporteTable.setValueAt("", row, 2);
                reporteTable.setValueAt("", row, 3);
                reporteTable.setValueAt("", row, 4);
                reporteTable.setValueAt("", row, 5);
                reporteTable.setValueAt("", row, 6);

                String numfact = rs.getString("num_factura");
                String nombreC = rs.getString("nombreComp_caj");
                String codigo = rs.getString("codigo_caj");
                String fecha = rs.getString("fecha_emision");
                
                String cedula = rs.getString("Clientes_ci_cli");
                double total = rs.getDouble("total_pagar");
                double ganancia = rs.getDouble("ganancia_obtenida");
                

                reporteTable.setValueAt(numfact, row, 0);
                reporteTable.setValueAt(nombreC, row, 1);
                reporteTable.setValueAt(codigo, row, 2);
                reporteTable.setValueAt(fecha, row, 3);
                reporteTable.setValueAt(cedula, row, 4);
                reporteTable.setValueAt(total, row, 5);
                reporteTable.setValueAt(ganancia, row, 6);
                row++;

                //prueba de conexion
                nomCompletocaj=nombreC;
                System.out.println("Numero fact: " + numfact);
                System.out.println("Nombre: " + nombreC);
                System.out.println("Codigo cajero: " + codigo);
                System.out.println("fecha: " + fecha);
                System.out.println("cedula: " + cedula);
                System.out.println("total: " + total);
                System.out.println("Ganancias: "+ganancia);
                System.out.println("----------");
            }
        } catch (SQLException x) {
            throw new RuntimeException(x);
        }
    }//GEN-LAST:event_jButtonBuscarCajeroCodActionPerformed

    private void jButtonDesplegarCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesplegarCajerosActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try(Connection conn = DriverManager.getConnection(DB_URL, USER, PASSWORD)){
            String Query = "select cab.num_factura, \n" +
"		concat(caj.nombre_caj,' ',caj.apellido_caj) as nombreComp_caj, \n" +
                "        caj.codigo_caj, \n" +
                "        cab.fecha_emision, \n" +
                "        cab.Clientes_ci_cli, \n" +
                "        cab.total_pagar,\n" +
                "        cab.subtotal_fac - SUM(valcompra_prod * det.cantidad) AS ganancia_obtenida\n" +
                "from cabecera_fac cab \n" +
                "inner join cajeros caj on caj.codigo_caj = cab.Cajeros_codigo_caj\n" +
                "inner join detalle_fac det on det.Cabecera_Fac_num_factura = cab.num_factura\n" +
                "inner join productos pro on pro.codigo_prod = det.Productos_codigo_prod\n" +
                "group by cab.num_factura;";
            PreparedStatement stmt = conn.prepareStatement(Query);
            ResultSet rs = stmt.executeQuery();

            reporteTable.getModel();

            int row = 0;

            //prueba conexion
            while (rs.next()) {

                reporteTable.setValueAt("", row, 0);
                reporteTable.setValueAt("", row, 1);
                reporteTable.setValueAt("", row, 2);
                reporteTable.setValueAt("", row, 3);
                reporteTable.setValueAt("", row, 4);
                reporteTable.setValueAt("", row, 5);
                reporteTable.setValueAt("", row, 6);

                String numfact = rs.getString("num_factura");
                String nombreC = rs.getString("nombreComp_caj");
                String codigo = rs.getString("codigo_caj");
                String fecha = rs.getString("fecha_emision");
                
                String cedula = rs.getString("Clientes_ci_cli");
                double total = rs.getDouble("total_pagar");
                double ganancia = rs.getDouble("ganancia_obtenida");
                

                reporteTable.setValueAt(numfact, row, 0);
                reporteTable.setValueAt(nombreC, row, 1);
                reporteTable.setValueAt(codigo, row, 2);
                reporteTable.setValueAt(fecha, row, 3);
                reporteTable.setValueAt(cedula, row, 4);
                reporteTable.setValueAt(total, row, 5);
                reporteTable.setValueAt(ganancia, row, 6);
                row++;

                //prueba de conexion
                System.out.println("Numero fact: " + numfact);
                System.out.println("Nombre: " + nombreC);
                System.out.println("Codigo cajero: " + codigo);
                System.out.println("fecha: " + fecha);
                System.out.println("cedula: " + cedula);
                System.out.println("total: " + total);
                System.out.println("Ganancias: "+ganancia);
                System.out.println("----------");
            }
        } catch (SQLException x) {
            throw new RuntimeException(x);
        }
    }//GEN-LAST:event_jButtonDesplegarCajerosActionPerformed

    private void reporteCajeroBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteCajeroBtnMouseClicked
        
    }//GEN-LAST:event_reporteCajeroBtnMouseClicked

    private void reporteCajeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteCajeroBtnActionPerformed

           codCajero=codCajeroInput.getText();
           Document doc = new Document();
            try {
            FileOutputStream archivo;
            File file =new File("Reportes/Reporte_cajero_"+codCajero+".pdf");
            archivo=new FileOutputStream(file);
            PdfWriter.getInstance(doc, archivo);
            Image logo = Image.getInstance("src/Images/logo_2.png");
            logo.scaleToFit(200, 210);
            logo.setAlignment(Element.ALIGN_CENTER);
            
            PdfPTable title=new PdfPTable(3);
            title.setHorizontalAlignment(Element.ALIGN_MIDDLE);
            title.setWidthPercentage(100);
            float [] columnEnc=new float[]{80f,10f,80f};
            title.setWidths(columnEnc);
            Font fontEnc = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD);
            
            Paragraph t1=new Paragraph("\nReporte de Ventas Periódico\n\nVentas realizadas por cada cajero",fontEnc);
            t1.setIndentationRight(CENTER_ALIGNMENT);
            PdfPCell col3t1=new PdfPCell(t1);
            PdfPCell col2=new PdfPCell(new Phrase(""));
            PdfPCell col1img=new PdfPCell(logo);
            
            col1img.setBorder(0);
            col2.setBorder(0);
            col3t1.setBorderWidthTop(1f);
            col3t1.setBorderWidthBottom(1f);
            col3t1.setBorderWidthLeft(1f);
            col3t1.setBorderWidthRight(1f);
            col3t1.setPadding(2f);
            //title.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
            
            title.addCell(col1img);
            title.addCell(col2);
            title.addCell(col3t1);
            
            doc.open();
            doc.add(title);
            
            //datos cajero
              
                try {
                Connection conVentas = DriverManager.getConnection(DB_URL, USER, PASSWORD);
                String querycaj = "select count(*) as n_Ventas_caj from cabecera_fac CAB join cajeros CAJ on CAB.Cajeros_codigo_caj=CAJ.codigo_caj Where CAJ.codigo_caj=?;";

                PreparedStatement pst = conVentas.prepareStatement(querycaj);

                pst.setString(1,codCajero);

                ResultSet rs = pst.executeQuery();
                
                if (rs.next()) {
                    nVentascaj = rs.getInt("n_Ventas_caj");
                    System.out.println("n ventas:  " +codCajero+" "+nVentascaj);
                } 
                  
                // Cerrar ResultSet, PreparedStatement y Connection cuando hayas terminado
                rs.close();
                pst.close();
                conVentas.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            
            
             try {
                Connection contotalsinIva = DriverManager.getConnection(DB_URL, USER, PASSWORD);
                String querysinIva = "select codigo_caj, sum(DET.cantidad*PROD.valventa_prod) as sumaValor\n" +
                "	from detalle_fac DET, productos PROD, cajeros CAJ, cabecera_fac CAB\n" +
                "	WHERE DET.Productos_codigo_prod=PROD.codigo_prod and DET.Cabecera_Fac_num_factura=CAB.num_factura\n" +
                "    and CAB.Cajeros_codigo_caj=CAJ.codigo_caj and codigo_caj=?\n" +
                "group by codigo_caj;";

              
                PreparedStatement pst = contotalsinIva.prepareStatement(querysinIva);

                pst.setString(1,codCajero);

                ResultSet rs = pst.executeQuery();
                
                if (rs.next()) {
                    totalsinIva = rs.getDouble("sumaValor");
                    System.out.println("total sin iva:  " +codCajero+" "+totalsinIva);
                } 
                  

                // Cerrar ResultSet, PreparedStatement y Connection cuando hayas terminado
                rs.close();
                pst.close();
                contotalsinIva.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }    

             
             /*
        
             */
             
            
             try {
                Connection conGanancias = DriverManager.getConnection(DB_URL, USER, PASSWORD);
                String queryGanancia = "select cab.num_factura, codigo_caj, subtotal_fac-(sum(DET.cantidad*PROD.valcompra_prod)) as sumaGanancia\n" +
                "	from detalle_fac DET, productos PROD, cajeros CAJ, cabecera_fac CAB\n" +
                "	WHERE DET.Productos_codigo_prod=PROD.codigo_prod and DET.Cabecera_Fac_num_factura=CAB.num_factura\n" +
                "    and CAB.Cajeros_codigo_caj=CAJ.codigo_caj and codigo_caj=?\n" +
                "group by codigo_caj, cab.num_factura;";

              
                PreparedStatement pst = conGanancias.prepareStatement(queryGanancia);

                pst.setString(1,codCajero);

                ResultSet rs = pst.executeQuery();
                
                if (rs.next()) {
                    totalG = rs.getDouble("sumaGanancia");
                    System.out.println("Ganancias:  " +codCajero+" "+totalG);
                }
              // Cerrar ResultSet, PreparedStatement y Connection cuando hayas terminado
                rs.close();
                pst.close();
                conGanancias.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }  
            
             
             try {
                Connection conImpuestos = DriverManager.getConnection(DB_URL, USER, PASSWORD);
                String queryGanancia = "select codigo_caj, sum(iva_fac) as sumaImp\n" +
                "	from cajeros CAJ, cabecera_fac CAB\n" +
                "	WHERE CAB.Cajeros_codigo_caj=CAJ.codigo_caj and codigo_caj=?\n" +
                "group by codigo_caj;";

              
                PreparedStatement pst = conImpuestos.prepareStatement(queryGanancia);

                pst.setString(1,codCajero);

                ResultSet rs = pst.executeQuery();
                
                if (rs.next()) {
                    totalImp = rs.getDouble("sumaImp");
                    System.out.println("Total impuestos:  " +codCajero+" "+totalImp);
                }
              // Cerrar ResultSet, PreparedStatement y Connection cuando hayas terminado
                rs.close();
                pst.close();
                conImpuestos.close();
            } catch (SQLException e) {
                e.printStackTrace();
            } 
             
            
            
            Paragraph dataCaj1 =new Paragraph("\nNombres y apellidos del cajero: "+nomCompletocaj+"\n\n"+
            "Código de empleado: "+codCajero+"\n\n",fontEnc);
            
            
            Paragraph dataCaj2= new Paragraph("\nTotal ventas realizadas: "+nVentascaj+"\n\n"+
                    "Ganancias Obtenidas: "+totalG+"\n\n",fontEnc);
            
            
            PdfPTable cajero=new PdfPTable(3);
            cajero.setWidthPercentage(100);
            cajero.setWidths(columnEnc);
            PdfPCell col1 =new PdfPCell(dataCaj1);
            PdfPCell colcaj2=new PdfPCell(new Phrase(""));
            PdfPCell col3=new PdfPCell(dataCaj2);
            col1.setBorder(0);
            colcaj2.setBorder(0);
            col3.setBorder(0);
            cajero.getDefaultCell().setBorderWidth(1f);
            cajero.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
            cajero.addCell(col1);
            cajero.addCell(colcaj2);
            cajero.addCell(col3);
            PdfPTable cajeroCell = new PdfPTable(1);
            cajeroCell.addCell(cajero);
            cajeroCell.setWidthPercentage(100);
            cajeroCell.getDefaultCell().setBorderWidth(2f);
            
            Paragraph saltoLinea =new Paragraph();
            saltoLinea.add(new Phrase(Chunk.NEWLINE));
            doc.add(saltoLinea);
            doc.add(cajeroCell);
            doc.add(saltoLinea);
            
           //--Detalle reporte
            PdfPTable detReporte = new PdfPTable(6);
            detReporte.setWidthPercentage(100);
            float [] columnDet = new float[]{10f,33f,35f,17f,20f,20f};
            detReporte.setWidths(columnDet);
            detReporte.getDefaultCell().setBorderWidth(1f);
            detReporte.setHorizontalAlignment(Element.ALIGN_CENTER);
            detReporte.addCell("ITEM");
            detReporte.addCell("NOMBRE DEL PRODUCTO");
            detReporte.addCell("CÓDIGO DEL CÓDIGO PRODUCTO");
            detReporte.addCell("CANTIDAD");
            detReporte.addCell("VALOR UNITARIO");
            detReporte.addCell("VALOR TOTAL");
            
            // ...
            try {
                Connection con = DriverManager.getConnection(DB_URL, USER, PASSWORD);
                String queryDet = "SELECT\n" +
                        "    ROW_NUMBER() OVER (ORDER BY DET.Cabecera_Fac_num_factura) AS ITEM,\n" +
                        "    PROD.nombre_prod AS NOMBRE_PROD,\n" +
                        "    DET.Productos_codigo_prod AS COD_PROD,\n" +
                        "    DET.cantidad AS CANTIDAD,\n" +
                        "    PROD.valventa_prod AS PRECIO_UNI,\n" +
                        "    (PROD.valventa_prod * DET.cantidad) AS Valor_total\n" +
                        "FROM\n" +
                        "    cajeros CAJ\n" +
                        "JOIN\n" +
                        "    cabecera_fac CAB ON CAJ.codigo_caj = CAB.Cajeros_codigo_caj\n" +
                        "JOIN\n" +
                        "    detalle_fac DET ON CAB.num_factura = DET.Cabecera_Fac_num_factura\n" +
                        "JOIN\n" +
                        "    productos PROD ON DET.Productos_codigo_prod = PROD.codigo_prod\n" +
                        "WHERE\n" +
                        "    CAJ.codigo_caj = ?";

                PreparedStatement pst = con.prepareStatement(queryDet);
                pst.setString(1, codCajero);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    do {
                        // Agregar cada valor a la tabla detFact
                        detReporte.addCell(rs.getString("ITEM"));
                        detReporte.addCell(rs.getString("NOMBRE_PROD"));
                        detReporte.addCell(rs.getString("COD_PROD"));
                        detReporte.addCell(rs.getString("CANTIDAD"));
                        detReporte.addCell(rs.getString("PRECIO_UNI"));
                        detReporte.addCell(rs.getString("Valor_total"));
                    } while (rs.next());
                    doc.add(detReporte);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            //totales
           
            PdfPTable totalsinIvaT = new PdfPTable(2);
            totalsinIvaT.setHorizontalAlignment(Element.ALIGN_RIGHT);
            totalsinIvaT.setWidthPercentage(29.5f);
            float [] colTotales=new float[]{50f,50f};
            totalsinIvaT.setWidths(colTotales);
            totalsinIvaT.getDefaultCell().setBorderWidth(1f);
            totalsinIvaT.addCell(new Phrase("Total sin Iva:",fontEnc));
            totalsinIvaT.addCell(new Phrase("$"+totalsinIva, fontEnc));
            
            
            //iva
            PdfPTable iva = new PdfPTable(2);
            iva.setHorizontalAlignment(Element.ALIGN_RIGHT);
            iva.setWidthPercentage(29.5f);
            iva.setWidths(colTotales);
            iva.getDefaultCell().setBorderWidth(1f);
            iva.addCell(new Phrase("Impuestos generados:",fontEnc));
            iva.addCell(new Phrase("$"+totalImp, fontEnc));
          
            doc.add(totalsinIvaT);
            doc.add(iva);
            
            
        
            doc.close();
            archivo.close();
            Desktop.getDesktop().open(file);
            JOptionPane.showMessageDialog(null, "Reporte Creado");
            }catch(DocumentException | IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_reporteCajeroBtnActionPerformed

   



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codCajeroInput;
    private javax.swing.JMenu empleadosMenu;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JMenu inventarioMenu;
    private javax.swing.JButton jButtonBuscarCajeroCod;
    private javax.swing.JButton jButtonDesplegarCajeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reporteCajeroBtn;
    private javax.swing.JTable reporteTable;
    private javax.swing.JMenu reportesMenu;
    // End of variables declaration//GEN-END:variables
}
