/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author bryan
 */

public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    
    public static final String DB_URL = "jdbc:mysql://localhost/esfot-care";
    public static final String USER = "root";
    public static final String PASSWORD = "root2023";
    
    public static String codCajero;

    public Reportes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Reportes de Venta | Gestion Administrativa de ESFOT-Care+");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reporteTable = new javax.swing.JTable();
        codCajeroInput = new javax.swing.JTextField();
        jButtonBuscarCajeroCod = new javax.swing.JButton();
        reporteCajeroBtn = new javax.swing.JButton();
        reporteGeneralBtn = new javax.swing.JButton();
        jButtonDesplegarCajeros = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        empleadosMenu = new javax.swing.JMenu();
        inventarioMenu = new javax.swing.JMenu();
        reportesMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Buscar por código de cajero:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        reporteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Num Fact.", "Nombre del Cajero", "Cod. Cajero", "Fecha Emi.", "CI Cliente", "Total Vendido", "Ganancias obtenidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reporteTable);
        if (reporteTable.getColumnModel().getColumnCount() > 0) {
            reporteTable.getColumnModel().getColumn(0).setResizable(false);
            reporteTable.getColumnModel().getColumn(1).setResizable(false);
            reporteTable.getColumnModel().getColumn(2).setResizable(false);
            reporteTable.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 1130, 390));

        codCajeroInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        codCajeroInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codCajeroInputActionPerformed(evt);
            }
        });
        getContentPane().add(codCajeroInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 130, 30));

        jButtonBuscarCajeroCod.setText("Buscar");
        jButtonBuscarCajeroCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCajeroCodActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarCajeroCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 90, 30));

        reporteCajeroBtn.setBackground(new java.awt.Color(204, 255, 204));
        reporteCajeroBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reporteCajeroBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-alt.png"))); // NOI18N
        reporteCajeroBtn.setText("   Generar reporte por cajero");
        reporteCajeroBtn.setActionCommand("  Agregar Producto");
        reporteCajeroBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteCajeroBtnMouseClicked(evt);
            }
        });
        reporteCajeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteCajeroBtnActionPerformed(evt);
            }
        });
        getContentPane().add(reporteCajeroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 270, -1));

        reporteGeneralBtn.setBackground(new java.awt.Color(255, 153, 153));
        reporteGeneralBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reporteGeneralBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report_1.png"))); // NOI18N
        reporteGeneralBtn.setText("   Generar reporte general de ventas");
        reporteGeneralBtn.setActionCommand("  Agregar Producto");
        reporteGeneralBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteGeneralBtnMouseClicked(evt);
            }
        });
        reporteGeneralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteGeneralBtnActionPerformed(evt);
            }
        });
        getContentPane().add(reporteGeneralBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, 310, -1));

        jButtonDesplegarCajeros.setText("Desplegar todo");
        jButtonDesplegarCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesplegarCajerosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDesplegarCajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_2.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, 90));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jLabel4.setText("Reportes de Ventas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/radiant-gradient.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1200, 680));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_2.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, -1, -1));

        homeMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        homeMenu.setText("Inicio");
        homeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(homeMenu);

        empleadosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/users-alt.png"))); // NOI18N
        empleadosMenu.setText("Empleados");
        empleadosMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empleadosMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(empleadosMenu);

        inventarioMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box-open-full.png"))); // NOI18N
        inventarioMenu.setText("Inventario");
        inventarioMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventarioMenuMouseClicked(evt);
            }
        });
        inventarioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(inventarioMenu);

        reportesMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/books.png"))); // NOI18N
        reportesMenu.setText("Reportes");
        jMenuBar1.add(reportesMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign-out-alt.png"))); // NOI18N
        jMenu1.setText("Cerrar Sesión");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuMouseClicked
        this.setVisible(false);
        Home_Admin homin = new Home_Admin();
        homin.setVisible(true);
    }//GEN-LAST:event_homeMenuMouseClicked

    private void empleadosMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empleadosMenuMouseClicked

    }//GEN-LAST:event_empleadosMenuMouseClicked

    private void inventarioMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarioMenuMouseClicked
        Inventario inventario = new Inventario();
        inventario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_inventarioMenuMouseClicked

    private void inventarioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioMenuActionPerformed

    }//GEN-LAST:event_inventarioMenuActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void codCajeroInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codCajeroInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codCajeroInputActionPerformed

    private void jButtonBuscarCajeroCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCajeroCodActionPerformed
        // TODO add your handling code here:
        String codigoinput = codCajeroInput.getText();

        try(Connection conn = DriverManager.getConnection(DB_URL, USER, PASSWORD)){
            String Query = "SELECT * FROM cajeros WHERE codigo_caj = ?";
            PreparedStatement stmt = conn.prepareStatement(Query);
            stmt.setString(1, codigoinput);
            ResultSet rs = stmt.executeQuery();

            reporteTable.getModel();

            //Logica para busqueda
            int row = 0;

            if (rs.next()) {

                /*
                int rowc = 1;
                while(rowc > 10 ){
                    cajeroTable.setValueAt("", rowc, 0);
                    cajeroTable.setValueAt("", rowc, 1);
                    cajeroTable.setValueAt("", rowc, 2);
                    cajeroTable.setValueAt("", rowc, 3);
                    cajeroTable.setValueAt("", rowc, 4);
                    rowc++;
                }
                */

                int rowCount = reporteTable.getRowCount();
                for (int i = 1; i < rowCount; i++) {
                    for (int j = 0; j < 5; j++) {
                        reporteTable.setValueAt("", i, j);
                    }
                }

                String codigo = rs.getString("codigo_caj");
                String nombre = rs.getString("nombre_caj");
                String apellido = rs.getString("apellido_caj");
                String ci = rs.getString("ci_caj");
                String telefono = rs.getString("telefono_caj");
                String email = rs.getString("email_caj");
                String direccion = rs.getString("direccion_caj");
                String password = rs.getString("password_caj");
                String codigoAdmin = rs.getString("Administradores_codigo_admin");

                reporteTable.setValueAt(codigo, row, 0);
                reporteTable.setValueAt(nombre + " " + apellido, row, 1);
                reporteTable.setValueAt(ci, row, 2);
                reporteTable.setValueAt(telefono, row, 3);
                reporteTable.setValueAt(direccion, row, 4);

                //prueba de conexion
                System.out.println("Código: " + codigo);
                System.out.println("Nombre: " + nombre);
                System.out.println("Apellido: " + apellido);
                System.out.println("CI: " + ci);
                System.out.println("Teléfono: " + telefono);
                System.out.println("Email: " + email);
                System.out.println("Dirección: " + direccion);
                System.out.println("Password: " + password);
                System.out.println("Código de Admin: " + codigoAdmin);
                System.out.println("----------");
            }
        } catch (SQLException x) {
            throw new RuntimeException(x);
        }
    }//GEN-LAST:event_jButtonBuscarCajeroCodActionPerformed

    private void jButtonDesplegarCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesplegarCajerosActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try(Connection conn = DriverManager.getConnection(DB_URL, USER, PASSWORD)){
            String Query = "SELECT * FROM cajeros";
            PreparedStatement stmt = conn.prepareStatement(Query);
            ResultSet rs = stmt.executeQuery();

            reporteTable.getModel();

            int row = 0;

            //prueba conexion
            while (rs.next()) {

                reporteTable.setValueAt("", row, 0);
                reporteTable.setValueAt("", row, 1);
                reporteTable.setValueAt("", row, 2);
                reporteTable.setValueAt("", row, 3);
                reporteTable.setValueAt("", row, 4);

                String codigo = rs.getString("codigo_caj");
                String nombre = rs.getString("nombre_caj");
                String apellido = rs.getString("apellido_caj");
                String ci = rs.getString("ci_caj");
                String telefono = rs.getString("telefono_caj");
                String email = rs.getString("email_caj");
                String direccion = rs.getString("direccion_caj");
                String password = rs.getString("password_caj");
                String codigoAdmin = rs.getString("Administradores_codigo_admin");

                reporteTable.setValueAt(codigo, row, 0);
                reporteTable.setValueAt(nombre + " " + apellido, row, 1);
                reporteTable.setValueAt(ci, row, 2);
                reporteTable.setValueAt(telefono, row, 3);
                reporteTable.setValueAt(direccion, row, 4);

                row++;

                //prueba de conexion
                System.out.println("Código: " + codigo);
                System.out.println("Nombre: " + nombre);
                System.out.println("Apellido: " + apellido);
                System.out.println("CI: " + ci);
                System.out.println("Teléfono: " + telefono);
                System.out.println("Email: " + email);
                System.out.println("Dirección: " + direccion);
                System.out.println("Password: " + password);
                System.out.println("Código de Admin: " + codigoAdmin);
                System.out.println("----------");
            }
        } catch (SQLException x) {
            throw new RuntimeException(x);
        }
    }//GEN-LAST:event_jButtonDesplegarCajerosActionPerformed

    private void reporteCajeroBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteCajeroBtnMouseClicked
        
    }//GEN-LAST:event_reporteCajeroBtnMouseClicked

    private void reporteCajeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteCajeroBtnActionPerformed

           codCajero=codCajeroInput.getText();
           Document doc = new Document();
            try {
            FileOutputStream archivo;
            File file =new File("Reportes/Reporte_cajero_"+codCajero+".pdf");
            archivo=new FileOutputStream(file);
            PdfWriter.getInstance(doc, archivo);
            Image logo = Image.getInstance("src/Images/logo_2.png");
            logo.scaleToFit(200, 210);
            logo.setAlignment(Element.ALIGN_CENTER);
            
            PdfPTable title=new PdfPTable(3);
            title.setHorizontalAlignment(Element.ALIGN_MIDDLE);
            title.setWidthPercentage(100);
            float [] columnEnc=new float[]{80f,10f,80f};
            title.setWidths(columnEnc);
            Font fontEnc = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD);
            
            Paragraph t1=new Paragraph("\nReporte de Ventas Periódico\n\nVentas realizadas por cada cajero",fontEnc);
            t1.setIndentationRight(CENTER_ALIGNMENT);
            PdfPCell col3t1=new PdfPCell(t1);
            PdfPCell col2=new PdfPCell(new Phrase(""));
            PdfPCell col1img=new PdfPCell(logo);
            
            col1img.setBorder(0);
            col2.setBorder(0);
            col3t1.setBorderWidthTop(1f);
            col3t1.setBorderWidthBottom(1f);
            col3t1.setBorderWidthLeft(1f);
            col3t1.setBorderWidthRight(1f);
            col3t1.setPadding(2f);
            //title.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
            
            title.addCell(col1img);
            title.addCell(col2);
            title.addCell(col3t1);
            
            doc.open();
            doc.add(title);
            
            //datos cajero
            
            Paragraph dataCaj1 =new Paragraph("\nNombres y apellidos del cajero: "+"\n\n"+
            "Código de empleado: "+"\n\n",fontEnc);
            
            
            Paragraph dataCaj2= new Paragraph("\nTotal ventas realizadas: "+"\n\n"+
                    "Ganancias Obtenidas: "+"\n\n",fontEnc);
            
            
            PdfPTable cajero=new PdfPTable(3);
            cajero.setWidthPercentage(100);
            cajero.setWidths(columnEnc);
            PdfPCell col1 =new PdfPCell(dataCaj1);
            PdfPCell colcaj2=new PdfPCell(new Phrase(""));
            PdfPCell col3=new PdfPCell(dataCaj2);
            col1.setBorder(0);
            colcaj2.setBorder(0);
            col3.setBorder(0);
            cajero.getDefaultCell().setBorderWidth(1f);
            cajero.getDefaultCell().setBorder(PdfPCell.NO_BORDER);
            cajero.addCell(col1);
            cajero.addCell(colcaj2);
            cajero.addCell(col3);
            PdfPTable cajeroCell = new PdfPTable(1);
            cajeroCell.addCell(cajero);
            cajeroCell.setWidthPercentage(100);
            cajeroCell.getDefaultCell().setBorderWidth(2f);
            
            Paragraph saltoLinea =new Paragraph();
            saltoLinea.add(new Phrase(Chunk.NEWLINE));
            doc.add(saltoLinea);
            doc.add(cajeroCell);
            doc.add(saltoLinea);
           
           //--Detalle reporte
            PdfPTable detReporte = new PdfPTable(6);
            detReporte.setWidthPercentage(100);
            float [] columnDet = new float[]{10f,33f,35f,17f,20f,20f};
            detReporte.setWidths(columnDet);
            detReporte.getDefaultCell().setBorderWidth(1f);
            detReporte.setHorizontalAlignment(Element.ALIGN_CENTER);
            detReporte.addCell("ITEM");
            detReporte.addCell("NOMBRE DEL PRODUCTO");
            detReporte.addCell("CÓDIGO DEL CÓDIGO PRODUCTO");
            detReporte.addCell("CANTIDAD");
            detReporte.addCell("VALOR UNITARIO");
            detReporte.addCell("VALOR TOTAL");
            
            // ...
            try {
                Connection con = DriverManager.getConnection(DB_URL, USER, PASSWORD);
                String queryDet = "SELECT\n" +
                        "    ROW_NUMBER() OVER (ORDER BY DET.Cabecera_Fac_num_factura) AS ITEM,\n" +
                        "    PROD.nombre_prod AS NOMBRE_PROD,\n" +
                        "    DET.Productos_codigo_prod AS COD_PROD,\n" +
                        "    DET.cantidad AS CANTIDAD,\n" +
                        "    PROD.valventa_prod AS PRECIO_UNI,\n" +
                        "    (PROD.valventa_prod * DET.cantidad) AS Valor_total\n" +
                        "FROM\n" +
                        "    cajeros CAJ\n" +
                        "JOIN\n" +
                        "    cabecera_fac CAB ON CAJ.codigo_caj = CAB.Cajeros_codigo_caj\n" +
                        "JOIN\n" +
                        "    detalle_fac DET ON CAB.num_factura = DET.Cabecera_Fac_num_factura\n" +
                        "JOIN\n" +
                        "    productos PROD ON DET.Productos_codigo_prod = PROD.codigo_prod\n" +
                        "WHERE\n" +
                        "    CAJ.codigo_caj = ?";

                PreparedStatement pst = con.prepareStatement(queryDet);
                pst.setString(1, codCajero);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    do {
                        // Agregar cada valor a la tabla detFact
                        detReporte.addCell(rs.getString("ITEM"));
                        detReporte.addCell(rs.getString("NOMBRE_PROD"));
                        detReporte.addCell(rs.getString("COD_PROD"));
                        detReporte.addCell(rs.getString("CANTIDAD"));
                        detReporte.addCell(rs.getString("PRECIO_UNI"));
                        detReporte.addCell(rs.getString("Valor_total"));
                    } while (rs.next());
                    doc.add(detReporte);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
// ...

            
            //totales
           
            PdfPTable totalsinIva = new PdfPTable(2);
            totalsinIva.setHorizontalAlignment(Element.ALIGN_RIGHT);
            totalsinIva.setWidthPercentage(29.5f);
            float [] colTotales=new float[]{50f,50f};
            totalsinIva.setWidths(colTotales);
            totalsinIva.getDefaultCell().setBorderWidth(1f);
            totalsinIva.addCell(new Phrase("Total sin Iva:",fontEnc));
            totalsinIva.addCell(new Phrase("$", fontEnc));
            
            
            //iva
            PdfPTable iva = new PdfPTable(2);
            iva.setHorizontalAlignment(Element.ALIGN_RIGHT);
            iva.setWidthPercentage(29.5f);
            iva.setWidths(colTotales);
            iva.getDefaultCell().setBorderWidth(1f);
            iva.addCell(new Phrase("Impuestos generados:",fontEnc));
            iva.addCell(new Phrase("$", fontEnc));
          
            doc.add(totalsinIva);
            doc.add(iva);
        
            doc.close();
            archivo.close();
            Desktop.getDesktop().open(file);
            JOptionPane.showMessageDialog(null, "Reporte Creado");
            }catch(DocumentException | IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_reporteCajeroBtnActionPerformed

    private void reporteGeneralBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteGeneralBtnMouseClicked
        
    }//GEN-LAST:event_reporteGeneralBtnMouseClicked

    private void reporteGeneralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteGeneralBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reporteGeneralBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codCajeroInput;
    private javax.swing.JMenu empleadosMenu;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JMenu inventarioMenu;
    private javax.swing.JButton jButtonBuscarCajeroCod;
    private javax.swing.JButton jButtonDesplegarCajeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reporteCajeroBtn;
    private javax.swing.JButton reporteGeneralBtn;
    private javax.swing.JTable reporteTable;
    private javax.swing.JMenu reportesMenu;
    // End of variables declaration//GEN-END:variables
}
